services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    network_mode: host
    environment:
      # PUID: $USER_ID
      # PGID: $GROUP_ID
      TZ: $TIMEZONE
    ports:
      - 3000:3000
    volumes:
      - ../provision/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    # Wait for all the things we get status on
    depends_on:
      - qbittorrent
      - radarr
      - sonarr
      - prowlarr
      - gluetun
      - plex