services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    # profiles: ["media", "all"]
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      #- "33400:33400/tcp"
    volumes:
      - ../provision/plex:/config
      - ../content/media:/data/media
    environment:
      PUID: $USER_ID
      PGID: $GROUP_ID
      TZ: $TIMEZONE
      VERSION: docker
      HOSTNAME: PlexServer
      PLEX_UID: $USER_ID
      PLEX_GID: $GROUP_ID
      # PLEX_CLAIM: claim-xxxxxxxxxxxx
    privileged: true # libusb_init failed

    labels:
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=http://localhost:32400
      - homepage.description=Plex
      - homepage.weight=0
      - homepage.widget.type=plex
      - homepage.widget.url=http://localhost:32400
      - homepage.widget.key=${PLEX_TOKEN}