services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      PUID: $USER_ID
      PGID: $GROUP_ID
      TZ: $TIMEZONE
      WEBUI_PORT: 8090
    volumes:
      - ../provision/qbittorrent:/config
      - ../content/torrents:/data/torrents
    network_mode: service:gluetun
    # depends_on:
    #   gluetun:
    #     condition: service_healthy
    restart: unless-stopped
    labels:
    #   - autoheal=true
      - homepage.group=Download
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://localhost:8090
      - homepage.description=Bittorrent client
      - homepage.weight=2
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://localhost:8090
      - homepage.widget.username=${QBITTORRENT_USERNAME}
      - homepage.widget.password=${QBITTORRENT_PASSWORD}
    healthcheck:
      test: curl google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3