services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: $USER_ID
      PGID: $GROUP_ID
      TZ: $TIMEZONE
    volumes:
      - ../provision/sonarr:/config
      - ../content:/data
    # ports:
    #   - "8989:8989"
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      - qbittorrent
    # networks:
    #   - media-network
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://localhost:8989
      - homepage.description=Series management
      - homepage.weight=0
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://localhost:8989
      - homepage.widget.key=${SONARR_API_KEY}
    healthcheck:
      test: curl --fail http://127.0.0.1:8989/sonarr/ping
      interval: 30s
      retries: 10